import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LanguageContext = createContext({
    language: 'en',
    setLanguage: () => {},
    t: (key) => key,
});

const TRANSLATIONS = {
    en: {
        'nav.home': 'Home',
        'nav.about': 'About',
        'nav.findFood': 'Find Food',
        'nav.getHelp': 'Get Help',
        'nav.partners': 'Partners',
        'nav.contact': 'Contact',
        'home.card.findFood.title': 'Find Food Resources',
        'home.card.findFood.desc': 'Search our comprehensive directory of food banks, soup kitchens, and pantries in your area.',
        'home.card.findFood.button': 'Search Resources',
        'home.card.getHelp.title': 'Get Help Now',
        'home.card.getHelp.desc': 'Need immediate assistance? Access emergency resources and connect to help 24/7.',
        'home.card.getHelp.button': 'Get Help',
        'home.card.partners.title': 'Partner With Us',
        'home.card.partners.desc': 'Food banks and organizations can join our network to reach more people in need.',
        'home.card.partners.button': 'Become a Partner',
        'home.features.title': 'Key Features',
        'home.features.desc': 'Our platform connects people to food resources through accessible, private, and efficient tools.',
        'home.features.search.title': 'Smart Search',
        'home.features.search.desc': 'Search by location, resource type, or services offered. Filter results to find exactly what you need.',
        'home.features.search.badge': 'Real-time location filtering',
        'home.features.privacy.title': 'Privacy First',
        'home.features.privacy.desc': 'Your search history and location are never stored or shared. Access resources safely and privately.',
        'home.features.privacy.badge': 'Zero data tracking',
        'home.features.access.title': '24/7 Access',
        'home.features.access.desc': 'Find help anytime, anywhere. Our platform is always available when you need it most.',
        'home.features.access.badge': 'Always available',
        'home.cta.badge': 'Take Action Against Hunger',
        'home.cta.title': 'Ready to Make a Difference?',
        'home.cta.desc': 'Join our mission to end hunger. Whether you need help or want to help others, 5 Star Solutions connects us all.',
        'home.cta.button1': 'Find Food Resources',
        'home.cta.button2': 'Become a Partner',
        'home.tagline': 'The Power Of Five Can Feed Many.',
        'hero.badge': '5 Star Solutions',
        'hero.title1': 'The Power of Five',
        'hero.title2': 'Can Feed Many',
        'hero.subtitle': 'Connecting people to local food banks, soup kitchens, and pantries—',
        'hero.highlight1': 'fast',
        'hero.highlight2': 'private',
        'hero.highlight3': 'accessible',
        'hero.and': 'and',
        'hero.button1': 'Find Food',
        'hero.button2': 'Get Help Now',
        'home.heroTitle': '5 Star Solutions',
        'home.heroSubtitle': 'A Zero Hunger platform that connects people to local food banks, soup kitchens, and pantries—fast, private, and accessible.',
        'home.cta.findFood': 'Find Food Near Me',
        'home.cta.getHelp': 'Get Help Now',
        'home.section.howItWorks': 'How it works',
        'home.section.howItWorks.1.title': 'Search',
        'home.section.howItWorks.1.body': 'Enter a city or zip code to see nearby free food resources.',
        'home.section.howItWorks.2.title': 'Filter',
        'home.section.howItWorks.2.body': 'Filter by pantry, soup kitchen, eligibility, and open hours.',
        'home.section.howItWorks.3.title': 'Go',
        'home.section.howItWorks.3.body': 'Get directions, call ahead, and save favorites.',
        'about.title': 'About 5 Star Solutions',
        'about.body': 'We are a student-led capstone team building an enterprise-style platform for SDG 2: Zero Hunger. Our goal is to streamline access to safe, nutritious food by mapping local resources and making them accessible in multiple languages.',
        'about.header': 'About Us',
        'about.heroTitle': 'Building a Hunger-Free Future',
        'about.heroDesc': '5 Star Solutions is an enterprise-level platform dedicated to supporting SDG 2: Zero Hunger by connecting people to local food resources.',
        'about.mission.title': 'Our Mission',
        'about.mission.desc': 'To build an accessible directory of free food resources that connects people in need to local food banks, soup kitchens, and pantries—fast, private, and accessible to all.',
        'about.sdg.title': 'SDG 2: Zero Hunger',
        'about.sdg.desc': 'We are dedicated to supporting the United Nations Sustainable Development Goal 2: Zero Hunger, working towards a world where no one goes hungry.',
        'about.community.title': 'Community First',
        'about.community.desc': 'Our platform is built by the community, for the community. We partner with local organizations to ensure accurate, up-to-date information.',
        'about.stats.partners': 'Partner Organizations',
        'about.stats.served': 'People Served Monthly',
        'about.stats.languages': 'Languages Supported',
        'about.stats.access': 'Access Available',
        'about.values.title': 'Our Values',
        'about.values.accessibility.title': 'Accessibility',
        'about.values.accessibility.desc': 'Everyone deserves access to food resources. Our platform is designed to be inclusive and easy to use for all.',
        'about.values.efficiency.title': 'Efficiency',
        'about.values.efficiency.desc': 'Quick search, instant results. We help people find the help they need without unnecessary delays.',
        'about.values.privacy.title': 'Privacy',
        'about.values.privacy.desc': 'Your search history and location are never stored or shared. We prioritize your privacy and safety.',
        'about.sdg.section.title': 'Supporting the UN Sustainable Development Goals',
        'about.sdg.section.desc': 'The United Nations Sustainable Development Goal 2 aims to end hunger, achieve food security, improve nutrition, and promote sustainable agriculture by 2030. 5 Star Solutions is committed to contributing to this global goal by building accessible tools that connect people to food resources in their communities.',
        'about.sdg.button': 'Learn More About SDG 2',
        'about.footer': '5 Star Solutions is a capstone project demonstrating how technology can address real-world challenges and support the UN Sustainable Development Goals.',
        'resources.title': 'Find Food',
        'resources.searchPlaceholder': 'Search by city, zip code, or resource name...',
        'resources.filters.type': 'Type',
        'resources.filters.all': 'All',
        'resources.filters.pantry': 'Food Pantry',
        'resources.filters.soupKitchen': 'Soup Kitchen',
        'resources.filters.meal': 'Meal Program',
        'resources.card.services': 'Services',
        'resources.card.hours': 'Hours',
        'resources.card.phone': 'Phone',
        'resources.card.address': 'Address',
        'resources.card.directions': 'Directions',
        'getHelp.title': 'Get Help Now',
        'getHelp.body': 'If you need food today, start here. Use this page to find immediate resources and next steps.',
        'getHelp.action.findFood': 'Search Food Resources',
        'getHelp.action.call211': 'Call 2-1-1 (United Way)',
        'getHelp.action.emergency': 'Emergency: Call 9-1-1',
        'partners.title': 'Partner With Us',
        'partners.body': 'Food banks, pantries, and community kitchens can partner with 5 Star Solutions to keep information accurate and help more people faster.',
        'contact.title': 'Contact',
        'contact.body': 'Reach out for partnerships, technical support, or volunteering opportunities.',
        'footer.mission': 'Building an accessible directory of free food resources to support SDG 2: Zero Hunger.',
    },
    es: {
        'nav.home': 'Inicio',
        'nav.about': 'Acerca de',
        'nav.findFood': 'Encontrar Comida',
        'nav.getHelp': 'Obtener Ayuda',
        'nav.partners': 'Socios',
        'nav.contact': 'Contacto',
        'home.card.findFood.title': 'Encontrar Recursos de Comida',
        'home.card.findFood.desc': 'Busca nuestro directorio completo de bancos de alimentos, comedores y despensas en tu área.',
        'home.card.findFood.button': 'Buscar Recursos',
        'home.card.getHelp.title': 'Obtener Ayuda Ahora',
        'home.card.getHelp.desc': '¿Necesitas asistencia inmediata? Accede a recursos de emergencia y conecta con ayuda 24/7.',
        'home.card.getHelp.button': 'Obtener Ayuda',
        'home.card.partners.title': 'Asóciate Con Nosotros',
        'home.card.partners.desc': 'Los bancos de alimentos y organizaciones pueden unirse a nuestra red para llegar a más personas necesitadas.',
        'home.card.partners.button': 'Conviértete en Socio',
        'home.features.title': 'Características Clave',
        'home.features.desc': 'Nuestra plataforma conecta a las personas con recursos de alimentos a través de herramientas accesibles, privadas y eficientes.',
        'home.features.search.title': 'Búsqueda Inteligente',
        'home.features.search.desc': 'Busca por ubicación, tipo de recurso o servicios ofrecidos. Filtra resultados para encontrar exactamente lo que necesitas.',
        'home.features.search.badge': 'Filtrado de ubicación en tiempo real',
        'home.features.privacy.title': 'Privacidad Primero',
        'home.features.privacy.desc': 'Tu historial de búsqueda y ubicación nunca se almacenan ni comparten. Accede a recursos de manera segura y privada.',
        'home.features.privacy.badge': 'Sin seguimiento de datos',
        'home.features.access.title': 'Acceso 24/7',
        'home.features.access.desc': 'Encuentra ayuda en cualquier momento, en cualquier lugar. Nuestra plataforma siempre está disponible cuando más la necesitas.',
        'home.features.access.badge': 'Siempre disponible',
        'home.cta.badge': 'Toma Acción Contra el Hambre',
        'home.cta.title': '¿Listo para Hacer la Diferencia?',
        'home.cta.desc': 'Únete a nuestra misión para acabar con el hambre. Ya sea que necesites ayuda o quieras ayudar a otros, 5 Star Solutions nos conecta a todos.',
        'home.cta.button1': 'Encontrar Recursos de Comida',
        'home.cta.button2': 'Conviértete en Socio',
        'home.tagline': 'El poder de cinco puede alimentar a muchos.',
        'hero.badge': '5 Star Solutions',
        'hero.title1': 'El Poder de Cinco',
        'hero.title2': 'Puede Alimentar a Muchos',
        'hero.subtitle': 'Conectando a las personas con bancos de alimentos, comedores y despensas—',
        'hero.highlight1': 'rápido',
        'hero.highlight2': 'privado',
        'hero.highlight3': 'accesible',
        'hero.and': 'y',
        'hero.button1': 'Encontrar Comida',
        'hero.button2': 'Obtener Ayuda Ahora',
        'home.heroTitle': '5 Star Solutions',
        'home.heroSubtitle': 'Una plataforma de Hambre Cero que conecta a las personas con bancos de alimentos, comedores comunitarios y despensas—rápido, privado y accesible.',
        'home.cta.findFood': 'Encontrar Comida Cerca',
        'home.cta.getHelp': 'Necesito Ayuda Ahora',
        'home.section.howItWorks': 'Cómo funciona',
        'home.section.howItWorks.1.title': 'Buscar',
        'home.section.howItWorks.1.body': 'Ingresa una ciudad o código postal para ver recursos gratuitos cercanos.',
        'home.section.howItWorks.2.title': 'Filtrar',
        'home.section.howItWorks.2.body': 'Filtra por despensa, comedor, elegibilidad y horarios.',
        'home.section.howItWorks.3.title': 'Ir',
        'home.section.howItWorks.3.body': 'Obtén direcciones, llama antes y guarda favoritos.',
        'about.title': 'Acerca de 5 Star Solutions',
        'about.body': 'Somos un equipo estudiantil creando una plataforma de nivel empresarial para el ODS 2: Hambre Cero. Nuestro objetivo es simplificar el acceso a alimentos seguros y nutritivos mediante un mapa de recursos locales y soporte multilingüe.',
        'about.header': 'Acerca de Nosotros',
        'about.heroTitle': 'Construyendo un Futuro Sin Hambre',
        'about.heroDesc': '5 Star Solutions es una plataforma de nivel empresarial dedicada a apoyar el ODS 2: Hambre Cero conectando a las personas con recursos locales de alimentos.',
        'about.mission.title': 'Nuestra Misión',
        'about.mission.desc': 'Construir un directorio accesible de recursos de comida gratis que conecte a las personas necesitadas con bancos de alimentos, comedores y despensas—rápido, privado y accesible para todos.',
        'about.sdg.title': 'ODS 2: Hambre Cero',
        'about.sdg.desc': 'Estamos dedicados a apoyar el Objetivo de Desarrollo Sostenible 2 de las Naciones Unidas: Hambre Cero, trabajando hacia un mundo donde nadie pase hambre.',
        'about.community.title': 'Comunidad Primero',
        'about.community.desc': 'Nuestra plataforma es construida por la comunidad, para la comunidad. Nos asociamos con organizaciones locales para asegurar información precisa y actualizada.',
        'about.stats.partners': 'Organizaciones Socias',
        'about.stats.served': 'Personas Atendidas Mensualmente',
        'about.stats.languages': 'Idiomas Soportados',
        'about.stats.access': 'Acceso Disponible',
        'about.values.title': 'Nuestros Valores',
        'about.values.accessibility.title': 'Accesibilidad',
        'about.values.accessibility.desc': 'Todos merecen acceso a recursos de alimentos. Nuestra plataforma está diseñada para ser inclusiva y fácil de usar para todos.',
        'about.values.efficiency.title': 'Eficiencia',
        'about.values.efficiency.desc': 'Búsqueda rápida, resultados instantáneos. Ayudamos a las personas a encontrar la ayuda que necesitan sin retrasos innecesarios.',
        'about.values.privacy.title': 'Privacidad',
        'about.values.privacy.desc': 'Tu historial de búsqueda y ubicación nunca se almacenan ni comparten. Priorizamos tu privacidad y seguridad.',
        'about.sdg.section.title': 'Apoyando los Objetivos de Desarrollo Sostenible de la ONU',
        'about.sdg.section.desc': 'El Objetivo de Desarrollo Sostenible 2 de las Naciones Unidas tiene como objetivo acabar con el hambre, lograr la seguridad alimentaria, mejorar la nutrición y promover la agricultura sostenible para 2030. 5 Star Solutions está comprometido a contribuir a este objetivo global construyendo herramientas accesibles que conecten a las personas con recursos de alimentos en sus comunidades.',
        'about.sdg.button': 'Aprende Más Sobre el ODS 2',
        'about.footer': '5 Star Solutions es un proyecto de demostración que muestra cómo la tecnología puede abordar desafíos del mundo real y apoyar los Objetivos de Desarrollo Sostenible de la ONU.',
        'resources.title': 'Encontrar Comida',
        'resources.searchPlaceholder': 'Buscar por ciudad, código postal o nombre...',
        'resources.filters.type': 'Tipo',
        'resources.filters.all': 'Todos',
        'resources.filters.pantry': 'Despensa',
        'resources.filters.soupKitchen': 'Comedor',
        'resources.filters.meal': 'Programa de Comidas',
        'resources.card.services': 'Servicios',
        'resources.card.hours': 'Horario',
        'resources.card.phone': 'Teléfono',
        'resources.card.address': 'Dirección',
        'resources.card.directions': 'Direcciones',
        'getHelp.title': 'Obtener Ayuda Ahora',
        'getHelp.body': 'Si necesitas comida hoy, comienza aquí. Usa esta página para encontrar recursos inmediatos y próximos pasos.',
        'getHelp.action.findFood': 'Buscar Recursos',
        'getHelp.action.call211': 'Llamar 2-1-1 (United Way)',
        'getHelp.action.emergency': 'Emergencia: Llamar 9-1-1',
        'partners.title': 'Asóciate Con Nosotros',
        'partners.body': 'Bancos de alimentos, despensas y cocinas comunitarias pueden asociarse con 5 Star Solutions para mantener información precisa y ayudar a más personas.',
        'contact.title': 'Contacto',
        'contact.body': 'Contáctanos para asociaciones, soporte técnico u oportunidades de voluntariado.',
        'footer.mission': 'Creando un directorio accesible de recursos de comida gratis para apoyar el ODS 2: Hambre Cero.',
    },
};

export function LanguageProvider({ children, defaultLanguage = 'en', storageKey = 'fivestar-language' }) {
    const [language, setLanguage] = useState(() => {
        if (typeof window !== 'undefined') {
            return localStorage.getItem(storageKey) || defaultLanguage;
        }
        return defaultLanguage;
    });

    useEffect(() => {
        if (typeof window !== 'undefined') {
            localStorage.setItem(storageKey, language);
        }
    }, [language, storageKey]);

    const t = useMemo(() => {
        const table = TRANSLATIONS[language] || TRANSLATIONS.en;
        return (key) => table[key] || TRANSLATIONS.en[key] || key;
    }, [language]);

    const value = useMemo(() => ({ language, setLanguage, t }), [language, t]);

    return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
    return useContext(LanguageContext);
}
